import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import { CONFIG } from "src/config/config";
// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: CONFIG.GOOGLE_SHEET.SERVICE_ACCOUNT_EMAIL,
  key: CONFIG.GOOGLE_SHEET.PRIVATE_KEY,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const tabName = "Users";
const range = "A:H";

const connectGoogleSheet = async () => {
  const document = new GoogleSpreadsheet(CONFIG.GOOGLE_SHEET.SHEET_ID, {
    apiKey: "AIzaSyCGHOjBZq15PowPKXQ5MVqv-VOwbB1ymCk",
  });
  return document;
};

export const loadInfo = async () => {
  const document = await connectGoogleSheet();
  await document.loadInfo();
  const sheet = document.sheetsByIndex[0];
  console.log("sheet", sheet);
};
