export const CONFIG = {
  PORT: process.env.PORT || 4000,

  REPLICATE_API_TOKEN: process.env.REPLICATE_API_TOKEN,
  REPLICATE_URL: process.env.REPLICATE_URL,

  BYTESCALE_PUBLIC_KEY: process.env.BYTESCALE_PUBLIC_KEY,
  BYTESCALE_PRIVATE_KEY: process.env.BYTESCALE_PRIVATE_KEY,
  BYTESCALE_ACCOUNT_ID: process.env.BYTESCALE_ACCOUNT_ID,

  MEETCODY_URL: process.env.MEETCODY_URL,
  MEETCODY_KEY: process.env.MEETCODY_KEY,
  MEETCODY_CONVERSATION_ID: process.env.MEETCODY_CONVERSATION_ID,

  GOOGLE_SHEET: {
    SERVICE_ACCOUNT_EMAIL: process.env.SERVICE_ACCOUNT_EMAIL,
    API_KEY: process.env.GOOGLE_APIKEY,
    PRIVATE_KEY: process.env.PRIVATE_KEY,
    SHEET_ID: process.env.SHEET_ID,
  },
};
